// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRZgvUbJUbGpCMpT5LpIE5EC77_Kujaps',
    appId: '1:823745149135:web:8ee2012b758f2b4dd61fba',
    messagingSenderId: '823745149135',
    projectId: 'auth-tutorial-221dd',
    authDomain: 'auth-tutorial-221dd.firebaseapp.com',
    storageBucket: 'auth-tutorial-221dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3V_zKKigWrBHDjhxSnU0Otxprn6PrblI',
    appId: '1:823745149135:android:02cfeb8c7c7ae76ed61fba',
    messagingSenderId: '823745149135',
    projectId: 'auth-tutorial-221dd',
    storageBucket: 'auth-tutorial-221dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApWp9ZSSUGjth9PuwazHGyiEYWOD4Gys4',
    appId: '1:823745149135:ios:94e0d88765ec7186d61fba',
    messagingSenderId: '823745149135',
    projectId: 'auth-tutorial-221dd',
    storageBucket: 'auth-tutorial-221dd.appspot.com',
    iosBundleId: 'com.example.googleAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApWp9ZSSUGjth9PuwazHGyiEYWOD4Gys4',
    appId: '1:823745149135:ios:94e0d88765ec7186d61fba',
    messagingSenderId: '823745149135',
    projectId: 'auth-tutorial-221dd',
    storageBucket: 'auth-tutorial-221dd.appspot.com',
    iosBundleId: 'com.example.googleAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRZgvUbJUbGpCMpT5LpIE5EC77_Kujaps',
    appId: '1:823745149135:web:0981776e4ff1d2a1d61fba',
    messagingSenderId: '823745149135',
    projectId: 'auth-tutorial-221dd',
    authDomain: 'auth-tutorial-221dd.firebaseapp.com',
    storageBucket: 'auth-tutorial-221dd.appspot.com',
  );
}
